source "https://rubygems.org"
ruby "2.1.2"

gem "cuba"
gem "malone"
gem "mote"
gem "mote-render", require: "mote/render"
gem "ohm"
gem "ohm-contrib", require: "ohm/contrib"
gem "scrivener"
gem "shield"
