- category: "Food"
  name: "Cheese"
- category: "Food"
  name: "Chocolate"
- category: "Food"
  name: "Skip dinner"
- category: "Drink"
  name: "Cofee"
- category: "Drink"
  name: "Soda"
- category: "Drink"
  name: "Acoholic beverages"
- category: "Symptoms"
  name: "Nausea or vomiting"
- category: "Symptoms"
  name: "Sensitive to light, noise, smell"
- category: "Body Changes"
  name: "Mentruation or Skip menstruation"
- category: "Body Changes"
  name: "Stress"
- category: "Medication"
  name: "Ergotamin"
- category: "Medication"
  name: "Exedrin"
- category: "Medication"
  name: "Aspirin"
